# fly.toml app configuration file generated for greeny-insight-backend on 2023-11-15T00:10:52+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "greeny-insight-backend"
primary_region = "ams"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
